---
- name: download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb
    dest: /tmp/grafana_5.4.2_amd64.deb

- name: install grafana
  apt: deb="/tmp/grafana_5.4.2_amd64.deb"

- name: start grafana service
  command: systemctl start grafana-server

- name: enable grafana service
  command: systemctl enable grafana-server
